# Generated by Django 5.0.4 on 2024-06-26 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image1', models.ImageField(upload_to='./Gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='./author')),
                ('altTag', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='blogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='./blog')),
                ('altTag', models.CharField(blank=True, max_length=100)),
                ('slug', models.CharField(max_length=50)),
                ('page_title', models.CharField(blank=True, max_length=100)),
                ('meta', models.CharField(blank=True, max_length=200)),
                ('index', models.CharField(choices=[('index', 'index'), ('noindex', 'noindex')], default='index', max_length=8)),
                ('follow', models.CharField(choices=[('follow', 'follow'), ('nofollow', 'nofollow')], default='follow', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('count', models.IntegerField()),
                ('icon', models.ImageField(upload_to='./counter/')),
                ('iconAlt', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('page_title', models.CharField(max_length=200)),
                ('meta', models.CharField(max_length=300)),
                ('slug', models.CharField(max_length=100)),
                ('index', models.CharField(choices=[('index', 'index'), ('noindex', 'noindex')], default='index', max_length=8)),
                ('follow', models.CharField(choices=[('follow', 'follow'), ('nofollow', 'nofollow')], default='follow', max_length=8)),
                ('bannerImage', models.ImageField(blank=True, upload_to='./')),
                ('bannerImageAlt', models.CharField(blank=True, max_length=150)),
                ('bannerHeading', models.CharField(blank=True, max_length=100)),
                ('aboutSection', models.CharField(blank=True, max_length=100, verbose_name='About Field')),
                ('aboutbgImage', models.ImageField(blank=True, upload_to='./', verbose_name='Background Image')),
                ('aboutContent', models.CharField(blank=True, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='travelGuideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('heading', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('icon', models.ImageField(upload_to='./guideline')),
                ('altTag', models.CharField(blank=True, max_length=100)),
                ('bannerImage', models.ImageField(upload_to='./guideline')),
                ('banneraltTag', models.CharField(blank=True, max_length=100)),
                ('slug', models.CharField(max_length=20)),
                ('page_title', models.CharField(blank=True, max_length=100)),
                ('meta', models.CharField(blank=True, max_length=200)),
                ('index', models.CharField(choices=[('index', 'index'), ('noindex', 'noindex')], default='index', max_length=8)),
                ('follow', models.CharField(choices=[('follow', 'follow'), ('nofollow', 'nofollow')], default='follow', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('bannerImage', models.ImageField(upload_to='./blog')),
                ('altTag', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('slug', models.SlugField()),
                ('page_title', models.CharField(max_length=200)),
                ('meta', models.CharField(max_length=400)),
                ('status', models.CharField(choices=[('1', 'Draft'), ('2', 'Published')], default=1, max_length=2)),
                ('index', models.CharField(choices=[('index', 'index'), ('noindex', 'noindex')], default='index', max_length=8)),
                ('follow', models.CharField(choices=[('follow', 'follow'), ('nofollow', 'nofollow')], default='follow', max_length=8)),
                ('featured', models.CharField(blank=True, max_length=10)),
                ('image1', models.ImageField(blank=True, upload_to='./blog')),
                ('image2', models.ImageField(blank=True, upload_to='./blog')),
                ('image3', models.ImageField(blank=True, upload_to='./blog')),
                ('image4', models.ImageField(blank=True, upload_to='./blog')),
                ('image5', models.ImageField(blank=True, upload_to='./blog')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.blogcategory')),
            ],
        ),
    ]
