# Generated by Django 5.0.4 on 2024-06-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
